// Generated by scripts/strategy_comparisons.py from recorded
// strategy-lane batch and suite manifests: per-(model, lane) trace
// rubric pass counts. Regenerate; do not hand-edit.
export interface ModelLaneStat {
  model: string;
  lane: string;
  attempted: number;
  passed: number;
}

export const MODEL_LANE_STATS: ModelLaneStat[] = [
  {
    "model": "gpt-5.5",
    "lane": "fast",
    "attempted": 39,
    "passed": 38
  },
  {
    "model": "gpt-5.5",
    "lane": "ladder",
    "attempted": 20,
    "passed": 19
  },
  {
    "model": "gpt-5.5",
    "lane": "ladder_v2",
    "attempted": 6,
    "passed": 6
  },
  {
    "model": "gpt-5.5",
    "lane": "median3",
    "attempted": 13,
    "passed": 12
  },
  {
    "model": "gpt-5.6",
    "lane": "ladder",
    "attempted": 1,
    "passed": 1
  },
  {
    "model": "gpt-5.6-luna",
    "lane": "fast",
    "attempted": 18,
    "passed": 5
  },
  {
    "model": "gpt-5.6-luna",
    "lane": "ladder",
    "attempted": 6,
    "passed": 0
  },
  {
    "model": "gpt-5.6-luna",
    "lane": "ladder_v2",
    "attempted": 6,
    "passed": 5
  },
  {
    "model": "gpt-5.6-luna",
    "lane": "median3",
    "attempted": 6,
    "passed": 1
  },
  {
    "model": "gpt-5.6-sol",
    "lane": "fast",
    "attempted": 18,
    "passed": 18
  },
  {
    "model": "gpt-5.6-sol",
    "lane": "ladder",
    "attempted": 6,
    "passed": 5
  },
  {
    "model": "gpt-5.6-sol",
    "lane": "ladder_v2",
    "attempted": 6,
    "passed": 6
  },
  {
    "model": "gpt-5.6-sol",
    "lane": "median3",
    "attempted": 6,
    "passed": 6
  },
  {
    "model": "gpt-5.6-terra",
    "lane": "fast",
    "attempted": 18,
    "passed": 18
  },
  {
    "model": "gpt-5.6-terra",
    "lane": "ladder",
    "attempted": 6,
    "passed": 0
  },
  {
    "model": "gpt-5.6-terra",
    "lane": "ladder_v2",
    "attempted": 6,
    "passed": 6
  },
  {
    "model": "gpt-5.6-terra",
    "lane": "median3",
    "attempted": 6,
    "passed": 6
  }
];
