"""Generate public lab projection contracts without changing scientific identities."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

from .lab_contracts import RESPONSE_MODELS
from .schema import _typescript


def schema_document():
    definitions = {}
    roots = []
    for model in RESPONSE_MODELS:
        document = model.model_json_schema(by_alias=True)
        for name, definition in document.pop("$defs", {}).items():
            if name in definitions and definitions[name] != definition:
                raise ValueError("conflicting lab schema definition")
            definitions[name] = definition
        definitions[model.__name__] = document
        roots.append({"$ref": f"#/$defs/{model.__name__}"})
    return {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "title": "Thesis lab read API v1",
        "$defs": dict(sorted(definitions.items())),
        # Empty list responses legitimately share a structural envelope. The
        # endpoint chooses a named response; the document union is inclusive.
        "anyOf": roots,
    }


def generate(*, check=False):
    root = Path(__file__).resolve().parents[1]
    document = schema_document()
    typescript = "// Generated by python -m thesis_core.lab_schema. Do not edit.\n\n"
    typescript += (
        "\n\n".join(
            f"export type {name} = {_typescript(value)};"
            for name, value in document["$defs"].items()
        )
        + "\n"
    )
    paths = (
        root / "thesis_core/schemas/lab.json",
        root / "site/src/data/generated/thesis-lab.ts",
        root / "site/src/data/generated/thesis-lab.schema.json",
    )
    for path, content in zip(
        paths,
        (
            json.dumps(document, indent=2) + "\n",
            typescript,
            json.dumps(document, indent=2) + "\n",
        ),
    ):
        if check:
            if not path.is_file() or path.read_text() != content:
                raise ValueError("lab generated contract drift")
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)
    return paths


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    try:
        generate(check=args.check)
    except ValueError as exc:
        parser.error(str(exc))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
