"""Generate JSON Schema and TypeScript from the scientific record registry."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

from .contracts import LINK_SPECS, RECORD_TYPES


def schema_document() -> dict[str, Any]:
    definitions: dict[str, Any] = {}
    roots = []
    for kind, cls in sorted(RECORD_TYPES.items()):
        model = cls.model_json_schema(by_alias=True)
        for name, definition in model.pop("$defs", {}).items():
            if name in definitions and definitions[name] != definition:
                raise ValueError(f"conflicting schema definition {name}")
            definitions[name] = definition
        model["x-thesis-links"] = [
            dict(
                field=s.field,
                target_kind=s.target_kind,
                relation=s.relation,
                many=s.many,
                required=s.required,
            )
            for s in LINK_SPECS[kind]
        ]
        model["x-thesis-artifact-fields"] = list(cls.artifact_fields)
        definitions[cls.__name__] = model
        roots.append({"$ref": f"#/$defs/{cls.__name__}"})
    return {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "title": "Thesis scientific record",
        "$defs": dict(sorted(definitions.items())),
        "oneOf": roots,
    }


def _typescript(schema: dict[str, Any]) -> str:
    if "$ref" in schema:
        return schema["$ref"].rsplit("/", 1)[1]
    if "const" in schema:
        return json.dumps(schema["const"])
    if "enum" in schema:
        return " | ".join(json.dumps(x) for x in schema["enum"])
    if "anyOf" in schema or "oneOf" in schema:
        return " | ".join(
            _typescript(x) for x in schema.get("anyOf", schema.get("oneOf"))
        )
    kind = schema.get("type")
    if kind == "array":
        return f"ReadonlyArray<{_typescript(schema.get('items', {}))}>"
    if kind == "object":
        if "properties" not in schema:
            extra = schema.get("additionalProperties", {})
            rendered = _typescript(extra) if isinstance(extra, dict) else "unknown"
            return f"Readonly<Record<string, {rendered}>>"
        required = set(schema.get("required", []))
        fields = [
            f"readonly {json.dumps(name)}{'' if name in required else '?'}: "
            f"{_typescript(value)};"
            for name, value in schema["properties"].items()
        ]
        return "{\n  " + "\n  ".join(fields) + "\n}"
    return {
        "string": "string",
        "integer": "number",
        "number": "number",
        "boolean": "boolean",
        "null": "null",
    }.get(kind, "unknown")


def typescript_document(document: dict[str, Any] | None = None) -> str:
    document = document or schema_document()
    parts = ["// Generated by python -m thesis_core.schema. Do not edit."]
    parts.extend(
        f"export type {name} = {_typescript(definition)};"
        for name, definition in document["$defs"].items()
    )
    parts.append(
        "export type ScientificRecord = "
        + " | ".join(ref["$ref"].rsplit("/", 1)[1] for ref in document["oneOf"])
        + ";"
    )
    return "\n\n".join(parts) + "\n"


def generate(
    *, check: bool = False, output_dir: Path | None = None
) -> tuple[Path, Path]:
    root = Path(__file__).resolve().parents[1]
    paths = (
        (output_dir / "records.json", output_dir / "thesis-core.ts")
        if output_dir
        else (
            root / "thesis_core/schemas/records.json",
            root / "site/src/data/generated/thesis-core.ts",
        )
    )
    document = schema_document()
    contents = (
        json.dumps(document, indent=2, ensure_ascii=False) + "\n",
        typescript_document(document),
    )
    for path, text in zip(paths, contents):
        if check:
            if not path.is_file() or path.read_text() != text:
                raise ValueError(
                    f"generated contract drift: {path}; "
                    "run python -m thesis_core.schema"
                )
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text)
    return paths


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--output-dir", type=Path)
    parser.add_argument("--stdout", action="store_true")
    args = parser.parse_args()
    if args.stdout:
        print(json.dumps(schema_document(), indent=2))
    else:
        try:
            generate(check=args.check, output_dir=args.output_dir)
        except ValueError as exc:
            parser.error(str(exc))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
