#!/usr/bin/env python3
"""Publish strategy-lane runs as comparison-run augments.

Four lanes land here, all attached to EXISTING catalog cells so they are
graded against the same resolutions as the headline runs:

- ladder: reviewed runs elicited as a threshold ladder of binary
  exceedance probabilities (promptMode ladder); their published CDF is
  built from the ladder rungs, not from a normal-around-the-interval.
- rollouts: plain fast runs, three per target, relabeled so readers can
  tell the samples apart.
- median3: derived median-of-rollouts runs from
  scripts/median_rollout_ensemble.py, published with the exact median CDF.
- system_one: System One runs from scripts/run_system_one_forecast.py,
  asked either as a ladder of Noul threshold questions or as one Choice
  question over the ranges those rungs cut; the published CDF is the
  monotonized ladder or the cumulative bin sums. The lane has two backends
  and two elicitations and they are not the same mechanism, so the label and
  the description come from the runner itself: only a typesafe run is a
  System One run, and an adapter run says it emulates the interface over a
  named provider model.

Everything is emitted into site/src/data/thesis-strategy-comparisons.ts as
STRATEGY_COMPARISON_RUN_AUGMENTS, merged onto cells alongside the existing
recorded-run augments.

The command-line interface always rebuilds the complete trusted corpus: the
code-owned legacy index plus every committed strategy-suite manifest. Partial
lane publication is intentionally unavailable.

Usage:
    python3 scripts/strategy_comparisons.py \
        [--all-records] \
        [--out site/src/data/thesis-strategy-comparisons.ts]
"""

from __future__ import annotations

import argparse
import json
import pathlib
import sys
from typing import Any

ROOT = pathlib.Path(__file__).resolve().parents[1]
SCRIPTS = ROOT / "scripts"
DEFAULT_OUT = ROOT / "site" / "src" / "data" / "thesis-strategy-comparisons.ts"
LEGACY_INDEX = SCRIPTS / "strategy_comparison_legacy.json"
SUITES_ROOT = ROOT / "records" / "thesis-analyst" / "strategy-suites"
LEGACY_INDEX_SCHEMA = "thesis_strategy_legacy_index_v1"
SUITE_SCHEMA = "thesis_strategy_suite_v1"

# Suite manifests written before the System One lane existed carry exactly
# three lane keys; every suite written from now on also carries systemOne
# (null when the suite is ladder / median3 / both). Both shapes are trusted
# records, so the scanner accepts either and nothing else.
LEGACY_SUITE_LANE_KEYS = frozenset({"ladder", "rollouts", "median3"})
SUITE_LANE_KEYS = LEGACY_SUITE_LANE_KEYS | {"systemOne"}
SUITE_SELECTORS = frozenset({"ladder", "median3", "both", "system_one"})

SYSTEM_ONE_AGENT = "thesis.system_one"
SYSTEM_ONE_RUN_MODE = "system_one"
# A lane is the prompt mode the batch recorded, so the two elicitations are
# two lanes on /models: they ask the model different things and a single
# system_one column would pool them.
SYSTEM_ONE_PROMPT_MODES = {
    "noul_ladder": "system_one_noul_ladder",
    "choice_bins": "system_one_choice_bins",
}
SYSTEM_ONE_ELICITATION_BY_PROMPT_MODE = {
    mode: elicitation for elicitation, mode in SYSTEM_ONE_PROMPT_MODES.items()
}

sys.path.insert(0, str(SCRIPTS))
import run_system_one_forecast as system_one  # noqa: E402
from thesis_records_to_comparisons import (  # noqa: E402
    comparison_run,
    effective_scale,
    infer_runtime_model,
    repo_path,
    scaled,
    slugify,
    unsign_zero,
)


def write_strategy_ts(out_path: pathlib.Path, augments: dict) -> None:
    body = json.dumps(augments, indent=2, ensure_ascii=True)
    run_ats = sorted(
        run["predictionRun"]["runAt"]
        for runs in augments.values()
        for run in runs
    )
    wave_line = (
        f"// Wave: {run_ats[0][:10]} ({sum(len(r) for r in augments.values())} "
        f"runs across {len(augments)} cells, "
        f"{run_ats[0]} - {run_ats[-1]}).\n"
        if run_ats
        else ""
    )
    out_path.write_text(
        "// Generated by scripts/strategy_comparisons.py from recorded\n"
        "// strategy-lane manifests (ladder / rollouts / median3).\n"
        f"{wave_line}"
        "// Regenerate; do not hand-edit.\n"
        'import type { ForecastComparisonRun } from "./forecast-cells";\n\n'
        "export const STRATEGY_COMPARISON_RUN_AUGMENTS: Record<\n"
        "  string,\n"
        "  ForecastComparisonRun[]\n"
        f"> = {body};\n"
    )

MODEL_LANE_STATS_OUT = (
    ROOT / "site" / "src" / "data" / "model-lane-stats.generated.ts"
)


def _result_model(result: dict[str, Any]) -> str | None:
    """The model that answered one recorded result, or None."""

    manifest_path = result.get("manifestPath")
    if not manifest_path:
        return None
    manifest = json.loads(repo_path(manifest_path).read_text())
    model = infer_runtime_model(manifest)
    if not model:
        model = (manifest.get("agent") or {}).get("model")
    return str(model) if model else None


def _batch_model(batch: dict[str, Any]) -> str | None:
    for result in batch.get("results", []):
        model = _result_model(result)
        if model:
            return model
    return None


def build_model_lane_stats(
    *,
    legacy_index: pathlib.Path = LEGACY_INDEX,
    suites_root: pathlib.Path = SUITES_ROOT,
) -> list[dict[str, Any]]:
    """Per-(model, lane) rubric pass counts, derived only from records.

    A lane is the batch's promptMode (fast / ladder / ladder_v2) plus the
    suite-level median3 derivation. attempted counts every recorded run in
    the lane; passed counts runs whose sealed validation succeeded (only
    those become comparison rows). Failed medians live in suite manifests
    (ok=false rows), so they count as attempted too.
    """

    tally: dict[tuple[str, str], list[int]] = {}

    def bump(model: str | None, lane: str, *, attempted: int, passed: int) -> None:
        if not model or not attempted:
            return
        row = tally.setdefault((model, lane), [0, 0])
        row[0] += attempted
        row[1] += passed

    def bump_batch(batch_path: pathlib.Path) -> None:
        batch = json.loads(repo_path(str(batch_path)).read_text())
        results = batch.get("results", [])
        bump(
            _batch_model(batch),
            str(batch.get("promptMode") or "?"),
            attempted=len(results),
            passed=sum(1 for result in results if result.get("ok") is True),
        )

    for wave in load_legacy_waves(legacy_index):
        bump_batch(pathlib.Path(wave["ladderBatch"]))
        for path in wave["rolloutBatches"]:
            bump_batch(pathlib.Path(path))
        medians = [
            json.loads(repo_path(str(path)).read_text())
            for path in wave["medianManifests"]
        ]
        for manifest in medians:
            model = infer_runtime_model(manifest) or (
                (manifest.get("agent") or {}).get("model")
            )
            bump(str(model) if model else None, "median3", attempted=1, passed=1)

    if suites_root.exists():
        for path in sorted(suites_root.glob("????-??-??/strategy-*-a*.json")):
            suite = json.loads(path.read_text())
            if suite.get("schemaVersion") != SUITE_SCHEMA:
                continue
            lanes = suite.get("lanes") or {}
            ladder = lanes.get("ladder")
            suite_model: str | None = None
            if isinstance(ladder, dict) and ladder.get("batchManifest"):
                batch = json.loads(
                    repo_path(str(ladder["batchManifest"])).read_text()
                )
                suite_model = _batch_model(batch)
                results = batch.get("results", [])
                bump(
                    suite_model,
                    str(batch.get("promptMode") or "ladder"),
                    attempted=len(results),
                    passed=sum(
                        1 for result in results if result.get("ok") is True
                    ),
                )
            for row in lanes.get("rollouts") or []:
                if not isinstance(row, dict) or not row.get("batchManifest"):
                    continue
                batch = json.loads(
                    repo_path(str(row["batchManifest"])).read_text()
                )
                suite_model = suite_model or _batch_model(batch)
                results = batch.get("results", [])
                bump(
                    _batch_model(batch),
                    str(batch.get("promptMode") or "fast"),
                    attempted=len(results),
                    passed=sum(
                        1 for result in results if result.get("ok") is True
                    ),
                )
            median_rows = [
                row
                for row in (lanes.get("median3") or [])
                if isinstance(row, dict)
            ]
            bump(
                suite_model,
                "median3",
                attempted=len(median_rows),
                passed=sum(1 for row in median_rows if row.get("ok") is True),
            )
            # The System One lane runs its own model, never the suite's
            # analyst model, so it is tallied from its own batch alone and
            # never contributes to suite_model. It is also tallied per result
            # rather than per batch: a typesafe batch learns each model name
            # from the response it got, so one batch can legitimately hold
            # more than one, and a run that failed before any response names
            # none at all.
            system_one_lane = lanes.get("systemOne")
            if isinstance(system_one_lane, dict) and system_one_lane.get(
                "batchManifest"
            ):
                batch = json.loads(
                    repo_path(str(system_one_lane["batchManifest"])).read_text()
                )
                lane = str(
                    batch.get("promptMode")
                    or SYSTEM_ONE_PROMPT_MODES["noul_ladder"]
                )
                for result in batch.get("results", []):
                    bump(
                        _result_model(result),
                        lane,
                        attempted=1,
                        passed=1 if result.get("ok") is True else 0,
                    )

    return [
        {
            "model": model,
            "lane": lane,
            "attempted": attempted,
            "passed": passed,
        }
        for (model, lane), (attempted, passed) in sorted(tally.items())
    ]


def write_model_lane_stats(
    out_path: pathlib.Path, rows: list[dict[str, Any]]
) -> None:
    body = json.dumps(rows, indent=2, ensure_ascii=True)
    out_path.write_text(
        "// Generated by scripts/strategy_comparisons.py from recorded\n"
        "// strategy-lane batch and suite manifests: per-(model, lane) trace\n"
        "// rubric pass counts. Regenerate; do not hand-edit.\n"
        "export interface ModelLaneStat {\n"
        "  model: string;\n"
        "  lane: string;\n"
        "  attempted: number;\n"
        "  passed: number;\n"
        "}\n\n"
        f"export const MODEL_LANE_STATS: ModelLaneStat[] = {body};\n"
    )


POINT_COUNT = 201
MEDIAN3_ALGORITHM_VERSION = "pointwise_median_cdf_v1"


def batch_results(batch_paths: list[pathlib.Path]):
    for batch_path in batch_paths:
        batch = json.loads(repo_path(batch_path).read_text())
        for result in batch.get("results", []):
            if not result.get("ok"):
                continue
            target = result.get("target") or {}
            if not target.get("catalogSlug"):
                continue
            manifest = json.loads(repo_path(result["manifestPath"]).read_text())
            cells = json.loads(repo_path(result["cellsPath"]).read_text())
            if cells:
                yield target, manifest, cells[0]


def cdf_points_from_knots(
    knots: list[tuple[float, float]]
) -> list[dict[str, float]]:
    lower = knots[0][0]
    upper = knots[-1][0]
    step = (upper - lower) / (POINT_COUNT - 1)

    def cdf_at(value: float) -> float:
        if value <= knots[0][0]:
            return knots[0][1]
        for index in range(1, len(knots)):
            prev_value, prev_prob = knots[index - 1]
            knot_value, knot_prob = knots[index]
            if value <= knot_value:
                width = knot_value - prev_value
                if width <= 0:
                    return knot_prob
                return prev_prob + (value - prev_value) / width * (
                    knot_prob - prev_prob
                )
        return knots[-1][1]

    points = []
    for index in range(POINT_COUNT):
        value = upper if index == POINT_COUNT - 1 else lower + step * index
        points.append(
            {
                "value": round(value, 10) + 0.0,
                "probability": round(cdf_at(value), 10) + 0.0,
            }
        )
    return points


def ladder_distribution(
    cell: dict[str, Any], scale: float
) -> dict[str, Any] | None:
    ladder = cell.get("thresholdLadder")
    if not isinstance(ladder, dict):
        return None
    try:
        thresholds = [
            scaled(float(value), scale) for value in ladder["thresholds"]
        ]
        probs = [float(value) for value in ladder["cumulativeProbabilities"]]
    except (KeyError, TypeError, ValueError):
        return None
    if len(thresholds) != len(probs) or len(thresholds) < 3:
        return None

    point = scaled(cell["pointEstimate"], scale)
    ci_low = scaled(cell["ciLow"], scale)
    ci_high = scaled(cell["ciHigh"], scale)
    lower_spread = max(abs(float(point) - float(ci_low)), 1e-9)
    upper_spread = max(abs(float(ci_high) - float(point)), 1e-9)
    support_lower = min(float(ci_low) - lower_spread * 1.5, thresholds[0])
    support_upper = max(float(ci_high) + upper_spread * 1.5, thresholds[-1])

    knots: list[tuple[float, float]] = [(support_lower, 0.0)]
    previous_prob = 0.0
    for threshold, prob in zip(thresholds, probs):
        prob = min(max(prob, previous_prob), 1.0)
        if threshold <= knots[-1][0]:
            continue
        knots.append((threshold, prob))
        previous_prob = prob
    if support_upper > knots[-1][0]:
        knots.append((support_upper, 1.0))
    else:
        knots[-1] = (knots[-1][0], 1.0)

    points = cdf_points_from_knots(knots)
    return {
        "format": "numeric_cdf_v1",
        "pointCount": POINT_COUNT,
        "support": {
            "lower": points[0]["value"],
            "upper": points[-1]["value"],
        },
        "points": points,
        "summary": {
            "pointEstimate": unsign_zero(point),
            "median": unsign_zero(point),
            "interval80": {
                "lower": unsign_zero(ci_low),
                "upper": unsign_zero(ci_high),
            },
        },
        "provenance": "agent_reported",
    }


def ladder_augments(
    batch_paths: list[pathlib.Path],
) -> dict[str, list[dict[str, Any]]]:
    augments: dict[str, list[dict[str, Any]]] = {}
    for target, manifest, cell in batch_results(batch_paths):
        slug = target["catalogSlug"]
        scale = effective_scale(
            cell, target.get("valueScale", 1), target.get("targetUnit")
        )
        run = comparison_run(
            cell, manifest, slug, target.get("valueScale", 1),
            target.get("targetUnit"),
        )
        run["label"] = "Threshold-ladder elicitation"
        run["predictionRun"]["runLabel"] = "Threshold-ladder elicitation"
        run["description"] = (
            "Reviewed thesis.analyst run elicited as a ladder of binary "
            "exceedance probabilities (P(first print <= t) across 11-15 "
            "rungs); the point and interval are interpolated from the "
            "ladder and the published CDF is the ladder itself. Protocol "
            "adapted from Turtel et al. 2025 (arXiv:2505.17989). "
            + run["description"]
        )
        distribution = ladder_distribution(cell, scale)
        if distribution:
            run["predictionDistribution"] = distribution
        augments.setdefault(slug, []).append(run)
    return augments


def system_one_augments(
    batch_paths: list[pathlib.Path],
) -> dict[str, list[dict[str, Any]]]:
    """Project sealed System One runs as comparison runs.

    The lane is identified by the agent and the sealed run mode, not by the
    batch it was listed in, so a foreign manifest can never borrow the
    System One label. Everything the reader sees about the run comes from
    the manifest: the agent, the backend, the model, and the artifact
    inventory. The published CDF is the monotonized ladder itself.

    The label and the mechanism sentence are the runner's own
    (run_system_one_forecast.lane_label / lane_narrative), so the comparison
    row and the cell can never describe the run differently: an emulated
    run is labeled an emulation in both.
    """

    augments: dict[str, list[dict[str, Any]]] = {}
    for target, manifest, cell in batch_results(batch_paths):
        slug = target["catalogSlug"]
        agent = manifest.get("agent") or {}
        elicitation = SYSTEM_ONE_ELICITATION_BY_PROMPT_MODE.get(
            str(manifest.get("promptMode"))
        )
        if (
            manifest.get("runMode") != SYSTEM_ONE_RUN_MODE
            or elicitation is None
            or agent.get("agent") != SYSTEM_ONE_AGENT
        ):
            raise ValueError(
                f"system one lane holds a non-system-one run for {slug}"
            )
        backend = agent.get("backend")
        model = agent.get("model")
        if not backend or not model:
            raise ValueError(
                f"system one run for {slug} names no backend or model"
            )
        artifacts = manifest.get("artifacts") or []
        if not artifacts:
            raise ValueError(f"system one run for {slug} has no artifacts")
        value_scale = target.get("valueScale", 1)
        target_unit = target.get("targetUnit")
        scale = effective_scale(cell, value_scale, target_unit)
        run = comparison_run(cell, manifest, slug, value_scale, target_unit)
        rungs = len((cell.get("thresholdLadder") or {}).get("thresholds") or [])
        label = system_one.lane_label(str(backend), str(model), elicitation)
        run["variantId"] = (
            f"{slug}-thesis-system-one-{slugify(cell['runAt'])}"
        )
        run["label"] = label
        run["description"] = (
            system_one.lane_narrative(
                backend=str(backend),
                model=str(model),
                rungs=rungs,
                elicitation=elicitation,
            )
            + (
                " The published CDF is the cumulative bin sums themselves; "
                "the point estimate and the 80% interval are interpolated "
                "from it."
                if elicitation == "choice_bins"
                else " The published CDF is the monotonized ladder itself; "
                "the point estimate and the 80% interval are interpolated "
                "from it."
            )
            + (
                " Values converted to the catalog target unit."
                if scale != 1
                else ""
            )
        )
        prediction_run = run["predictionRun"]
        prediction_run["agent"] = SYSTEM_ONE_AGENT
        prediction_run["model"] = str(model)
        prediction_run["runLabel"] = label
        prediction_run["runDescription"] = (
            "Recorded thesis.system_one run promoted from the sealed "
            "manifest; the request, the raw response, and the ladder are "
            "in the activity log."
        )
        prediction_run["activityLog"] = artifacts
        distribution = ladder_distribution(cell, scale)
        if not distribution:
            raise ValueError(
                f"system one run for {slug} has no usable threshold ladder"
            )
        run["predictionDistribution"] = distribution
        augments.setdefault(slug, []).append(run)
    return augments


def rollout_augments(
    batch_paths: list[pathlib.Path],
) -> dict[str, list[dict[str, Any]]]:
    augments: dict[str, list[dict[str, Any]]] = {}
    for target, manifest, cell in batch_results(batch_paths):
        slug = target["catalogSlug"]
        run = comparison_run(
            cell, manifest, slug, target.get("valueScale", 1),
            target.get("targetUnit"),
        )
        augments.setdefault(slug, []).append(run)
    for slug, runs in augments.items():
        runs.sort(key=lambda run: run["predictionRun"]["runAt"])
        for index, run in enumerate(runs, start=1):
            label = f"Fast rollout {index} of {len(runs)}"
            run["label"] = label
            run["predictionRun"]["runLabel"] = label
            run["description"] = (
                "Independent fast rollout recorded for median prediction "
                "sampling (Turtel et al. 2025, arXiv:2505.17989). "
                + run["description"]
            )
    return augments


def indexed_rollout_augments(
    rollout_batches: list[tuple[int, pathlib.Path]],
) -> dict[str, list[dict[str, Any]]]:
    """Build fixed 1/2/3 labels within one suite, never across suites."""

    if [index for index, _path in rollout_batches] != [1, 2, 3]:
        raise ValueError("strategy suite rollouts must have indices 1, 2, 3")
    augments: dict[str, list[dict[str, Any]]] = {}
    for index, batch_path in rollout_batches:
        for target, manifest, cell in batch_results([batch_path]):
            slug = target["catalogSlug"]
            run = comparison_run(
                cell,
                manifest,
                slug,
                target.get("valueScale", 1),
                target.get("targetUnit"),
            )
            label = f"Fast rollout {index} of 3"
            run["label"] = label
            run["predictionRun"]["runLabel"] = label
            run["description"] = (
                "Independent fast rollout recorded for median prediction "
                "sampling (Turtel et al. 2025, arXiv:2505.17989). "
                + run["description"]
            )
            augments.setdefault(slug, []).append(run)
    return augments


def median_augments(
    manifest_paths: list[pathlib.Path],
    *,
    legacy: bool = False,
) -> dict[str, list[dict[str, Any]]]:
    augments: dict[str, list[dict[str, Any]]] = {}
    for manifest_path in manifest_paths:
        manifest = json.loads(repo_path(manifest_path).read_text())
        if not manifest.get("ok"):
            continue
        constituent_runs = manifest.get("constituentRuns") or []
        algorithm_version = manifest.get("aggregationAlgorithmVersion")
        if legacy:
            constituent_manifests = manifest.get("constituentManifests") or []
            if (
                len(constituent_manifests) != 3
                or len(set(constituent_manifests)) != 3
                or constituent_runs
                or algorithm_version
            ):
                raise ValueError(
                    f"invalid grandfathered median3 derivation {manifest_path}"
                )
        else:
            custody_roots = {
                reference.get("custodyRootSha256")
                for reference in constituent_runs
                if reference.get("custodyRootSha256")
            }
            manifest_refs = {
                reference.get("manifestPath")
                for reference in constituent_runs
                if reference.get("manifestPath")
            }
            if (
                len(constituent_runs) != 3
                or len(custody_roots) != 3
                or len(manifest_refs) != 3
                or algorithm_version != MEDIAN3_ALGORITHM_VERSION
            ):
                raise ValueError(
                    f"invalid median3 derivation {manifest_path}: expected "
                    "exactly 3 distinct custody-verifiable constituent run "
                    f"references and {MEDIAN3_ALGORITHM_VERSION}"
                )
        target = manifest.get("targetContext") or {}
        slug = target.get("catalogSlug")
        cells = json.loads(repo_path(manifest["cellsPath"]).read_text())
        if not slug or not cells:
            raise ValueError(f"median3 derivation lacks target/cell: {manifest_path}")
        cell = cells[0]
        scale = effective_scale(
            cell, target.get("valueScale", 1), target.get("targetUnit")
        )
        run = comparison_run(
            cell, manifest, slug, target.get("valueScale", 1),
            target.get("targetUnit"),
        )
        label = (
            "Median of 3 rollouts"
            if legacy
            else f"Median of {len(constituent_runs)} rollouts"
        )
        run["label"] = label
        run["predictionRun"]["runLabel"] = label
        if not legacy:
            run["predictionRun"]["aggregationAlgorithmVersion"] = (
                algorithm_version
            )
            run["predictionRun"]["constituentRuns"] = constituent_runs
            activity = cell.get("activityLog")
            if not isinstance(activity, list) or len(activity) != 4:
                raise ValueError(
                    f"median3 derivation lacks its verified parent activity: "
                    f"{manifest_path}"
                )
            run["predictionRun"]["activityLog"] = activity
        run["predictionRun"]["runDescription"] = (
            "Derived run: pointwise median of the constituent rollout CDFs "
            "(median prediction sampling, Turtel et al. 2025, "
            "arXiv:2505.17989). Deterministic aggregate of recorded "
            "rollouts; constituent manifests are in the activity log."
        )
        run["description"] = (
            "Pointwise median of three independent fast rollouts' CDFs — "
            "no new model call; the derived-distribution artifact and "
            "constituent manifests are recorded alongside the run."
        )
        distribution_path = None
        for artifact in manifest.get("artifacts", []):
            if artifact.get("artifactType") == "derived_distribution":
                distribution_path = artifact["path"]
        if not distribution_path:
            raise ValueError(
                f"median3 derivation lacks a distribution artifact: {manifest_path}"
            )
        distribution = json.loads(repo_path(distribution_path).read_text())
        if scale != 1:
            distribution["points"] = [
                {
                    "value": scaled(point["value"], scale),
                    "probability": point["probability"],
                }
                for point in distribution["points"]
            ]
            distribution["support"] = {
                "lower": scaled(distribution["support"]["lower"], scale),
                "upper": scaled(distribution["support"]["upper"], scale),
            }
            summary = distribution["summary"]
            distribution["summary"] = {
                "pointEstimate": scaled(summary["pointEstimate"], scale),
                "median": scaled(summary["median"], scale),
                "interval80": {
                    "lower": scaled(summary["interval80"]["lower"], scale),
                    "upper": scaled(summary["interval80"]["upper"], scale),
                },
            }
        run["predictionDistribution"] = distribution
        augments.setdefault(slug, []).append(run)
    return augments


def merge(
    *sources: dict[str, list[dict[str, Any]]]
) -> dict[str, list[dict[str, Any]]]:
    merged: dict[str, list[dict[str, Any]]] = {}
    for source in sources:
        for slug, runs in source.items():
            merged.setdefault(slug, []).extend(runs)
    for runs in merged.values():
        runs.sort(key=lambda run: run["predictionRun"]["runAt"])
    variant_ids: set[str] = set()
    for slug, runs in merged.items():
        for run in runs:
            variant_id = str(run.get("variantId") or "")
            if not variant_id or variant_id in variant_ids:
                raise ValueError(
                    f"duplicate or missing strategy variantId for {slug}: {variant_id}"
                )
            variant_ids.add(variant_id)
    return dict(sorted(merged.items()))


def load_legacy_waves(
    index_path: pathlib.Path = LEGACY_INDEX,
) -> list[dict[str, Any]]:
    payload = json.loads(index_path.read_text())
    if payload.get("schemaVersion") != LEGACY_INDEX_SCHEMA:
        raise ValueError("unsupported strategy legacy index")
    waves = payload.get("waves")
    if not isinstance(waves, list):
        raise ValueError("strategy legacy index has no wave list")
    normalized = []
    for wave in waves:
        if not isinstance(wave, dict):
            raise ValueError("strategy legacy wave is not an object")
        rollout_batches = wave.get("rolloutBatches")
        median_manifests = wave.get("medianManifests")
        if (
            not wave.get("ladderBatch")
            or not isinstance(rollout_batches, list)
            or len(rollout_batches) != 3
            or not isinstance(median_manifests, list)
        ):
            raise ValueError(f"invalid strategy legacy wave: {wave.get('waveId')}")
        paths = [wave["ladderBatch"], *rollout_batches, *median_manifests]
        if any(not repo_path(path).is_file() for path in paths):
            raise ValueError("strategy legacy wave references a missing file")
        normalized.append(wave)
    return normalized


def load_suite_waves(
    suites_root: pathlib.Path = SUITES_ROOT,
) -> list[dict[str, Any]]:
    waves: list[dict[str, Any]] = []
    if not suites_root.exists():
        return waves
    for path in sorted(suites_root.glob("????-??-??/strategy-*-a*.json")):
        suite = json.loads(path.read_text())
        if suite.get("schemaVersion") != SUITE_SCHEMA:
            raise ValueError(f"unsupported strategy suite manifest: {path}")
        selector = suite.get("suite")
        if selector not in SUITE_SELECTORS:
            raise ValueError(f"invalid suite selector in {path}")
        lanes = suite.get("lanes")
        if not isinstance(lanes, dict) or set(lanes) not in (
            set(LEGACY_SUITE_LANE_KEYS),
            set(SUITE_LANE_KEYS),
        ):
            raise ValueError(f"invalid strategy lane inventory in {path}")
        ladder = lanes["ladder"]
        ladder_batches = []
        if ladder is not None:
            if not isinstance(ladder, dict) or not ladder.get("batchManifest"):
                raise ValueError(f"invalid ladder lane in {path}")
            ladder_batches = [pathlib.Path(ladder["batchManifest"])]
        if selector in {"ladder", "both"} and not ladder_batches:
            raise ValueError(f"selected suite lacks its ladder lane in {path}")
        if selector in {"median3", "system_one"} and ladder_batches:
            raise ValueError(
                f"{selector}-only suite has a ladder lane in {path}"
            )
        rollout_rows = lanes["rollouts"]
        if not isinstance(rollout_rows, list):
            raise ValueError(f"invalid rollout lanes in {path}")
        rollout_batches = [
            (row.get("index"), pathlib.Path(str(row.get("batchManifest") or "")))
            for row in rollout_rows
            if isinstance(row, dict)
        ]
        expected_rollouts = [1, 2, 3] if selector in {"median3", "both"} else []
        if [index for index, _batch in rollout_batches] != expected_rollouts:
            raise ValueError(f"invalid rollout lane cardinality in {path}")
        median_rows = lanes["median3"]
        if not isinstance(median_rows, list):
            raise ValueError(f"invalid median3 lanes in {path}")
        if selector in {"ladder", "system_one"} and median_rows:
            raise ValueError(
                f"{selector}-only suite has median3 lanes in {path}"
            )
        median_paths = []
        for row in median_rows:
            if not isinstance(row, dict) or type(row.get("ok")) is not bool:
                raise ValueError(f"invalid median3 result in {path}")
            if row["ok"] is True:
                if not row.get("manifestPath") or row.get("error") is not None:
                    raise ValueError(f"passing median3 result is incomplete in {path}")
                median_paths.append(pathlib.Path(row["manifestPath"]))
            elif row.get("manifestPath") is not None or not row.get("error"):
                raise ValueError(f"failed median3 result is incomplete in {path}")
        system_one_lane = lanes.get("systemOne")
        system_one_batches: list[pathlib.Path] = []
        if system_one_lane is not None:
            if not isinstance(system_one_lane, dict) or not system_one_lane.get(
                "batchManifest"
            ):
                raise ValueError(f"invalid system one lane in {path}")
            system_one_batches = [
                pathlib.Path(str(system_one_lane["batchManifest"]))
            ]
        if selector == "system_one" and not system_one_batches:
            raise ValueError(
                f"selected suite lacks its system one lane in {path}"
            )
        if selector != "system_one" and system_one_batches:
            raise ValueError(
                f"{selector} suite carries a system one lane in {path}"
            )
        waves.append(
            {
                "ladderBatches": ladder_batches,
                "rolloutBatches": rollout_batches,
                "medianManifests": median_paths,
                "systemOneBatches": system_one_batches,
            }
        )
    return waves


def all_record_augments(
    *,
    legacy_index: pathlib.Path = LEGACY_INDEX,
    suites_root: pathlib.Path = SUITES_ROOT,
) -> dict[str, list[dict[str, Any]]]:
    wave_augments: list[dict[str, list[dict[str, Any]]]] = []
    for wave in load_legacy_waves(legacy_index):
        wave_augments.append(
            merge(
                ladder_augments([pathlib.Path(wave["ladderBatch"])]),
                # The legacy labels were assigned by runAt order. Preserve that
                # exact projection so the 2026-07-08 module remains byte-identical.
                rollout_augments(
                    [pathlib.Path(path) for path in wave["rolloutBatches"]]
                ),
                median_augments(
                    [pathlib.Path(path) for path in wave["medianManifests"]],
                    legacy=True,
                ),
            )
        )
    for wave in load_suite_waves(suites_root):
        wave_augments.append(
            merge(
                ladder_augments(wave["ladderBatches"]),
                indexed_rollout_augments(wave["rolloutBatches"])
                if wave["rolloutBatches"]
                else {},
                median_augments(wave["medianManifests"]),
                system_one_augments(wave["systemOneBatches"]),
            )
        )
    return merge(*wave_augments)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--all-records",
        action="store_true",
        help="compatibility flag; complete-corpus regeneration is always used",
    )
    parser.add_argument("--out", type=pathlib.Path, default=DEFAULT_OUT)
    args = parser.parse_args()

    augments = all_record_augments()
    write_strategy_ts(args.out, augments)
    total = sum(len(runs) for runs in augments.values())
    print(f"wrote {total} strategy runs across {len(augments)} cells -> {args.out}")
    stats = build_model_lane_stats()
    write_model_lane_stats(MODEL_LANE_STATS_OUT, stats)
    print(f"wrote {len(stats)} model-lane stat rows -> {MODEL_LANE_STATS_OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
